language: elixir

elixir:
  - '1.0.5'
otp_release: '17.4'

matrix:
  include:
    - elixir: '1.8.1'
      otp_release: '18.0'
script:
      - MIX_ENV=test mix do compile, test --cover --color

after_success:
      - bash <(curl -s https://codecov.io/bash)
